### ISSUE TITLE
Hello, World?

### ISSUE THREAD

**Issue by bwestergard** [crucialfelix/supercolliderjs-browser#1]
This looks really cool, but I'm not quite sure how to get started. I'm fairly familiar with scclang, very familiar with nodejs, but I'm a bit unclear on how to produce sound through code in the browser.

I'm running OSX 10.10.3. After cloning this repo (and running `npm install -g supercolliderjs` I can run `./bin/scapi` and see this nice interface:

![screen shot 2015-05-31 at 3 54 33 pm](https://cloud.githubusercontent.com/assets/915794/7903534/5e90fe1c-07ad-11e5-926a-1afb396967df.png)

Neither `sclang` nor `scsynth` are running (per `ps -A`). Running the following doesn't result in any log messages:

``` javascript
sc.call("server.boot", ["default"], function() { console.log(arguments); });
```

The terminal shows:

``` bash
Bjorns-MBP:supercolliderjs-browser bjornwestergard$ ./bin/scapi.js 
Listening on http://127.0.0.1:4040
Bad oscpath undefined
Missing error handler on `socket`.
undefined
```

**Comment by bwestergard** [comment]
Also tried starting `scsynth`/`sclang` before running `scapi`; in this case the last three lines of the bash output above were not output, but still no responses from `sc.call` run in the browser.

**Comment by crucialfelix** [comment]
Yes, I split this off from supercollider.js and didn't have the time to document it properly.

See the comments at the top here:

https://github.com/crucialfelix/supercolliderjs-browser/blob/master/bin/scapi.js
- Start SuperCollider.app
- Install the API quark and recompile
- `API.mountDuplexOSC` // in sc
- `npm run scapi` // in terminal
- open http://localhost:4040/

It would be best if there was a single example command that did all of these. 

I was using this a lot last year, but I'm working on a quite different approach now. Honestly I'm not interested in sclang, just the server. I use javascript ES6 instead.

**Comment by bwestergard** [comment]
Thanks, looking forward to trying this out!

I too am interested in using ES6 to replace sclang as the language of composition. This project seems like it could be used that way; is that not the case? How does your current approach differ?

**Comment by crucialfelix** [comment]
I've done a few projects recently with ES6, so I will probably convert the
current classes over shortly.
it actually would have a few ES7 things like await async

Then I will make node id allocators, functions to create synths, groups etc.

But it will be all functional, not copies of the OOP classes we built back
then.

Especially tracking of server state would be done with Immutable or Mori
data structures.
RxJS for observeables.

input streams should be able to be mapped directly to synth events.

though in the node-js tradition I should keep supercollider.js small and
focused on just managing scsynth and sclang.
the other things should live in separate projects and people should be able
to mix and match and evolve the ideas into other ones.

one of the main problems with sc is that there is too much lock in and sunk
costs with the main library.

**Comment by bwestergard** [comment]
Agreed on all points.

**Comment by bwestergard** [comment]
Hm, tried all of the above and still didn't get any output (let alone sound) by running the following in the browser console:

``` javascript
sc.call("synth.new", ["beep", 100.0, 666.0, 7], function(synthID) {
  console.log('synthID', synthID);
});
```

**Comment by bwestergard** [comment]
Ah, got it working, key was to run `API.mountDuplexOSC` in sclang before running `scapi` at the terminal. The "connected" indicator refers to the browser's connection to the node app, not the node app's connection to sclang.

**Comment by bwestergard** [comment]
There seems to be about a 200-500ms delay between hitting enter in the browser console and hearing the new synth. Is that avoidable?

**Comment by bwestergard** [comment]
Found this thread where we discussed latency two years ago (I'd forgotten about this almost entirely): http://comments.gmane.org/gmane.comp.audio.supercollider.user/97115

**Comment by crucialfelix** [comment]
there shouldn't be any real latency. the websocket and osc are very fast.

I am on vacation for 5 days so might not be answering

**Comment by bwestergard** [comment]
Don't let me distract you from your vacation! Thanks a lot for putting all this together.

I'm consistently getting a 200ms delay for the simplest of OSC messages. I'll poke around a bit and see if I can figure out why.

![screen shot 2015-06-05 at 6 08 24 pm](https://cloud.githubusercontent.com/assets/915794/8016168/edd5aa10-0bad-11e5-8739-e7e935682649.png)

**Comment by crucialfelix** [comment]
btw. I switched the codebase to ES6 with babel, added some more unit
testing and got it up on travis.
