### ISSUE TITLE
callbacks on MIDI note events?

### ISSUE THREAD

**Issue by aspiers** [crucialfelix/supercolliderjs-browser#2]
Hi, thanks for sharing this stuff - looks really cool.

I'm fairly new to SuperCollider so forgive me if this is a dumb question.  Would it would be possible to use this project in order to receive events over a WebSocket from SuperCollider whenever it processes MIDI NoteOn events, and then render the notes being played in the browser using [VexFlow](http://www.vexflow.com/)?  I'd love the ability to generate live notation for a SC-handled MIDI stream, and using the browser plus existing HTML / Javascript libraries seems like a quick way to get that working cross-platform.  But obviously it relies on being able to capture this stream over a WebSocket.

Thanks for any light you can shed!

**Comment by crucialfelix** [comment]
I would leave supercollider out of this completely.  You can get MIDI events directly using: https://www.npmjs.com/package/midi in a node process.

Even better your browser can get MIDI events directly:
https://webaudio.github.io/web-midi-api/

Here is a usable simple wrapper:
https://github.com/mikaeljorhult/midi-events

So in your browser you can connect directly to midi and then use VexFlow.

In general I haven't tried too hard or wanted to try too hard to get supercollider into the browser. I do things in node or electron. The bridge between node and browser is never that simple and it confuses a lot of people.

**Comment by aspiers** [comment]
Just realised I never said thanks for this super helpful reply!  Season's greetings!
